"""initial

Revision ID: ea2e59677dbb
Revises: 
Create Date: 2026-06-03 23:22:54.962106

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2e59677dbb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_flags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_name', sa.String(), nullable=False),
    sa.Column('z_score', sa.Double(), nullable=False),
    sa.Column('value', sa.Double(), nullable=False),
    sa.Column('baseline_mean', sa.Double(), nullable=False),
    sa.Column('baseline_std', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomaly_flags_window_start', 'anomaly_flags', ['window_start'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('predicted_label', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=False),
    sa.Column('latency_ms', sa.Double(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classifications_created_at', 'classifications', ['created_at'], unique=False)
    op.create_index('ix_classifications_event_group', 'classifications', ['event_id', 'group'], unique=False)
    op.create_index('ix_classifications_group_model_created', 'classifications', ['group', 'model_name', 'created_at'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('case_queue_case_id', sa.String(), nullable=False),
    sa.Column('escalation_reason', sa.String(), nullable=False),
    sa.Column('confidence_max', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_escalations_created_at', 'escalations', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_escalations_created_at', table_name='escalations')
    op.drop_table('escalations')
    op.drop_index('ix_classifications_group_model_created', table_name='classifications')
    op.drop_index('ix_classifications_event_group', table_name='classifications')
    op.drop_index('ix_classifications_created_at', table_name='classifications')
    op.drop_table('classifications')
    op.drop_index('ix_anomaly_flags_window_start', table_name='anomaly_flags')
    op.drop_table('anomaly_flags')
    # ### end Alembic commands ###
