select
    id                      as play_id,
    game_id,
    play_number,
    quarter,
    down,
    distance,
    possession              as possession_program_id,
    play_type,
    yards_gained,
    field_pos_before,
    field_pos_after,
    score_home,
    score_away,
    description,
    -- attribution
    primary_player_id,
    secondary_player_id,
    tackler_player_id,
    ol_player_id,
    dl_player_id,
    lb_player_id,
    s_player_id,
    x_coord,
    y_coord,
    created_at
from {{ source('gridiron', 'play_log') }}
