"""initial

Revision ID: df9dd4bd52e1
Revises:
Create Date: 2026-06-15 21:16:03.621318

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df9dd4bd52e1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_library",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("document_text", sa.Text(), nullable=False),
        sa.Column("generation_model", sa.String(length=50), nullable=False),
        sa.Column("generation_tier", sa.Integer(), nullable=False),
        sa.Column("strategy", sa.String(length=50), nullable=False),
        sa.Column("harm_category", sa.String(length=50), nullable=False),
        sa.Column("is_harmful", sa.Boolean(), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=False),
        sa.Column("sovereign_verdict", sa.Boolean(), nullable=True),
        sa.Column("sovereign_confidence", sa.Float(), nullable=True),
        sa.Column("sovereign_reasoning", sa.Text(), nullable=True),
        sa.Column("verdict_correct", sa.Boolean(), nullable=True),
        sa.Column("target_condition_mix", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("served_none", sa.Integer(), nullable=False),
        sa.Column("served_tier_1", sa.Integer(), nullable=False),
        sa.Column("served_tier_2", sa.Integer(), nullable=False),
        sa.Column("served_tier_3", sa.Integer(), nullable=False),
        sa.CheckConstraint("generation_tier BETWEEN 1 AND 3", name="ck_generation_tier"),
        sa.CheckConstraint("phase BETWEEN 1 AND 3", name="ck_phase"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_document_library_generation_model",
        "document_library",
        ["generation_model"],
        unique=False,
    )
    op.create_index(
        "ix_document_library_harm_category", "document_library", ["harm_category"], unique=False
    )
    op.create_index(
        "ix_document_library_is_harmful", "document_library", ["is_harmful"], unique=False
    )
    op.create_index("ix_document_library_phase", "document_library", ["phase"], unique=False)
    op.create_index("ix_document_library_strategy", "document_library", ["strategy"], unique=False)
    op.create_table(
        "game_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_days", sa.Integer(), nullable=True),
        sa.Column("total_decisions", sa.Integer(), nullable=True),
        sa.Column("correct_decisions", sa.Integer(), nullable=True),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("phase_reached", sa.Integer(), nullable=True),
        sa.Column("game_over_condition", sa.String(length=30), nullable=True),
        sa.Column("final_bar_public_trust", sa.Integer(), nullable=True),
        sa.Column("final_bar_security", sa.Integer(), nullable=True),
        sa.Column("final_bar_treasury", sa.Integer(), nullable=True),
        sa.Column("final_bar_legitimacy", sa.Integer(), nullable=True),
        sa.Column("final_bar_compliance", sa.Integer(), nullable=True),
        sa.Column("total_agreements", sa.Integer(), nullable=True),
        sa.Column("total_overrides", sa.Integer(), nullable=True),
        sa.Column("total_no_agent_decisions", sa.Integer(), nullable=True),
        sa.Column("agreement_rate", sa.Float(), nullable=True),
        sa.Column("correct_agreements", sa.Integer(), nullable=True),
        sa.Column("correct_overrides", sa.Integer(), nullable=True),
        sa.Column("correct_no_agent", sa.Integer(), nullable=True),
        sa.Column("calibration_accuracy", sa.Float(), nullable=True),
        sa.Column("calibration_decisions", sa.Integer(), nullable=True),
        sa.Column("category_tiers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("agent_condition", sa.String(length=10), nullable=False),
        sa.Column("player_verdict", sa.String(length=10), nullable=False),
        sa.Column("player_correct", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("agreed_with_agent", sa.Boolean(), nullable=True),
        sa.Column("bar_public_trust", sa.Integer(), nullable=False),
        sa.Column("bar_security", sa.Integer(), nullable=False),
        sa.Column("bar_treasury", sa.Integer(), nullable=False),
        sa.Column("bar_legitimacy", sa.Integer(), nullable=False),
        sa.Column("bar_compliance", sa.Integer(), nullable=False),
        sa.Column("game_day", sa.Integer(), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=False),
        sa.Column("category_tier", sa.Integer(), nullable=False),
        sa.Column("is_calibration", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "player_verdict IN ('CLEAR', 'REDACT', 'ESCALATE')", name="ck_player_verdict"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document_library.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["game_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_player_decisions_agent_condition", "player_decisions", ["agent_condition"], unique=False
    )
    op.create_index(
        "ix_player_decisions_created_at", "player_decisions", ["created_at"], unique=False
    )
    op.create_index(
        "ix_player_decisions_document_id", "player_decisions", ["document_id"], unique=False
    )
    op.create_index(
        "ix_player_decisions_player_correct", "player_decisions", ["player_correct"], unique=False
    )
    op.create_index(
        "ix_player_decisions_session_id", "player_decisions", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_player_decisions_session_id", table_name="player_decisions")
    op.drop_index("ix_player_decisions_player_correct", table_name="player_decisions")
    op.drop_index("ix_player_decisions_document_id", table_name="player_decisions")
    op.drop_index("ix_player_decisions_created_at", table_name="player_decisions")
    op.drop_index("ix_player_decisions_agent_condition", table_name="player_decisions")
    op.drop_table("player_decisions")
    op.drop_table("game_sessions")
    op.drop_index("ix_document_library_strategy", table_name="document_library")
    op.drop_index("ix_document_library_phase", table_name="document_library")
    op.drop_index("ix_document_library_is_harmful", table_name="document_library")
    op.drop_index("ix_document_library_harm_category", table_name="document_library")
    op.drop_index("ix_document_library_generation_model", table_name="document_library")
    op.drop_table("document_library")
    # ### end Alembic commands ###
