"""add bias tables

Revision ID: 1bcb02dcc338
Revises: 002
Create Date: 2026-06-13 10:03:26.713807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1bcb02dcc338'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bias_probes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.String(length=20), nullable=False),
    sa.Column('government', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('probe_question_en', sa.Text(), nullable=False),
    sa.Column('divergence_hypothesis', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uix_bias_probes_topic_id', 'bias_probes', ['topic_id'], unique=True)
    op.create_table('bias_prompt_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('probe_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['probe_id'], ['bias_probes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uix_bias_prompt_variants_probe_language', 'bias_prompt_variants', ['probe_id', 'language'], unique=True)
    op.create_table('bias_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['bias_prompt_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uix_bias_responses_variant_model', 'bias_responses', ['variant_id', 'model_name'], unique=True)
    op.create_table('bias_divergence_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('probe_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('en_response_id', sa.UUID(), nullable=False),
    sa.Column('other_response_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('cosine_distance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['en_response_id'], ['bias_responses.id'], ),
    sa.ForeignKeyConstraint(['other_response_id'], ['bias_responses.id'], ),
    sa.ForeignKeyConstraint(['probe_id'], ['bias_probes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uix_bias_div_scores_probe_lang_model', 'bias_divergence_scores', ['probe_id', 'language', 'model_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('uix_bias_div_scores_probe_lang_model', table_name='bias_divergence_scores')
    op.drop_table('bias_divergence_scores')
    op.drop_index('uix_bias_responses_variant_model', table_name='bias_responses')
    op.drop_table('bias_responses')
    op.drop_index('uix_bias_prompt_variants_probe_language', table_name='bias_prompt_variants')
    op.drop_table('bias_prompt_variants')
    op.drop_index('uix_bias_probes_topic_id', table_name='bias_probes')
    op.drop_table('bias_probes')
