"""programs_schema

Revision ID: 33f31770f03e
Revises: 
Create Date: 2026-06-20 22:01:55.725130

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f31770f03e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conglomerates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.CHAR(length=3), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('network', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conglomerate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('emoji', sa.Text(), nullable=False),
    sa.Column('mascot', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('elo_seed_min', sa.SmallInteger(), nullable=False),
    sa.Column('elo_seed_max', sa.SmallInteger(), nullable=False),
    sa.Column('prestige', sa.SmallInteger(), nullable=False),
    sa.Column('founded_year', sa.SmallInteger(), nullable=False),
    sa.Column('primary_color', sa.CHAR(length=7), nullable=False),
    sa.Column('secondary_color', sa.CHAR(length=7), nullable=False),
    sa.Column('stadium_name', sa.Text(), nullable=False),
    sa.Column('stadium_cap', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('prestige BETWEEN 1 AND 5', name='ck_programs_prestige'),
    sa.CheckConstraint('tier IN (1, 2)', name='ck_programs_tier'),
    sa.ForeignKeyConstraint(['conglomerate_id'], ['conglomerates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programs')
    op.drop_table('conglomerates')
    # ### end Alembic commands ###
