"""initial

Revision ID: 715088b8a08a
Revises: 
Create Date: 2026-06-01 18:33:32.772818

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '715088b8a08a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate', name='casecategory'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'escalated', name='casestatus'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cases_category', 'cases', ['category'], unique=False)
    op.create_index('ix_cases_created_at', 'cases', ['created_at'], unique=False)
    op.create_index('ix_cases_severity', 'cases', ['severity'], unique=False)
    op.create_index('ix_cases_status', 'cases', ['status'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('actor_role', sa.Enum('reviewer', 'senior_reviewer', name='actorrole'), nullable=False),
    sa.Column('action', sa.Enum('approve', 'reject', 'escalate', name='action'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_actor_id', 'decisions', ['actor_id'], unique=False)
    op.create_index('ix_decisions_case_id', 'decisions', ['case_id'], unique=False)
    op.create_index('ix_decisions_created_at', 'decisions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_decisions_created_at', table_name='decisions')
    op.drop_index('ix_decisions_case_id', table_name='decisions')
    op.drop_index('ix_decisions_actor_id', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_cases_status', table_name='cases')
    op.drop_index('ix_cases_severity', table_name='cases')
    op.drop_index('ix_cases_created_at', table_name='cases')
    op.drop_index('ix_cases_category', table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
